name: Deploy Car-Parking-Frontend

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/github-actions-key
          chmod 600 ~/.ssh/github-actions-key
          ssh-keyscan -H SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh -i ~/.ssh/github-actions-key root@SERVER_IP << 'EOF'
            cd /var/www/html/Car-Parking-Frontend
            git pull origin main
            npm install
            pm2 stop car-parking-frontend || true
            PORT=4000 pm2 start "npm run dev" --name car-parking-frontend --watch --time
            pm2 save
            pm2 list
          EOF
